M48
; DRILL file {KiCad (6.0.5)} date Thu Jul 14 09:31:06 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-14T09:31:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X7.4Y-1.95
X7.4Y-2.05
X7.4Y-2.15
X7.4Y-2.25
X7.4Y-3.07
X7.4Y-3.17
X7.4Y-3.27
X7.4Y-3.37
T0
M30
